[tool.towncrier]
package = "plugin_template"
filename = "CHANGES.rst"
directory = "CHANGES/"
title_format = "{version} ({project_date})"
template = "CHANGES/.TEMPLATE.rst"
issue_format = "`#{issue} <https://pulp.plan.io/issues/{issue}>`_"

[tool.black]
line-length = 100
target-version = ["py36", "py37", "py38"]
exclude = '''
/(
    \.eggs
  | \.git
  | \.venv
  | _build
  | build
  | dist
  | migrations
  | docs
)/
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
line_length = 100
skip_glob= ["*/migrations/*"]
sections = "FUTURE,STDLIB,THIRDPARTY,PULPCORE,FIRSTPARTY,LOCALFOLDER"
known_pulpcore = "pulpcore,pulp_smash"
